#!/usr/bin/env ruby

def find_by_letter(count, word)
  letters = word.chars.uniq
  words = File.read("words.txt").split("\n") - ("b".."z").to_a + ["i"]
  words.select! do |w|
    w.size == count && w.chars.all? { |c| letters.include?(c) }
  end
  words
end

puts find_by_letter(Integer(ARGV[0]), ARGV[1]) unless $0.include?("_test.rb")
