#!/usr/bin/env ruby
count = Integer(ARGV[0])
letters = ARGV[1].chars.uniq
words = File.read("words.txt").split("\n") - ("b".."z").to_a + ["i"]
words.select! do |w|
  w.size == count && w.chars.all? { |c| letters.include?(c) }
end
puts words
